
"use client";
import DateField from "@/components/calenderform/DateField";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import {
  ArrowLeft, ArrowRight, Check, ClipboardList, FileText,
  Loader2, Package, Save, ShieldCheck, Truck, Users,
} from "lucide-react";

const RED = "#C8102E";
const BLUE = "#005F99";
const API = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000").replace(/\/$/, "");

type TabKey = "basic" | "customer" | "items" | "delivery" | "taxes" | "terms";
type RecordData = Record<string, any>;

type OrderLine = {
  item_id: string;
  item_code: string;
  item_name: string;
  uom: string;
  quantity: number;
  unit_price: number;
  discount_percent: number;
  tax_percent: number;
};

const TABS: { key: TabKey; label: string; icon: React.ElementType }[] = [
  { key: "basic", label: "SO Basic Info", icon: ClipboardList },
  { key: "customer", label: "Customer Details", icon: Users },
  { key: "items", label: "Item & Pricing", icon: Package },
  { key: "delivery", label: "Delivery & Logistics", icon: Truck },
  { key: "taxes", label: "Taxes & Charges", icon: FileText },
  { key: "terms", label: "Terms & Conditions", icon: ShieldCheck },
];

const inputClass =
  "w-full rounded-lg border border-gray-200 bg-white px-3 py-2.5 text-sm text-gray-900 outline-none focus:border-[#005F99] focus:ring-2 focus:ring-[#005F99]/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white";

const labelClass = "mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-200";

function getRows(value: any): RecordData[] {
  if (Array.isArray(value)) return value;
  for (const key of ["data", "rows", "customers", "items", "warehouses", "results"]) {
    if (Array.isArray(value?.[key])) return value[key];
  }
  return [];
}

function recordId(r: RecordData) {
  return String(r.customer_id ?? r.item_id ?? r.warehouse_id ?? r.id ?? "");
}

function customerName(c: RecordData) {
  return c.customer_name ?? c.name ?? c.display_name ?? "";
}

function itemName(i: RecordData) {
  return i.item_name ?? i.name ?? i.description ?? "";
}

function money(value: number, currency: string) {
  try {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: currency || "INR",
      maximumFractionDigits: 2,
    }).format(Number.isFinite(value) ? value : 0);
  } catch {
    return `${currency} ${(value || 0).toFixed(2)}`;
  }
}

function today() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

const newLine = (): OrderLine => ({
  item_id: "",
  item_code: "",
  item_name: "",
  uom: "EA",
  quantity: 1,
  unit_price: 0,
  discount_percent: 0,
  tax_percent: 18,
});

export default function SalesOrderPage() {
  const [activeTab, setActiveTab] = useState<TabKey>("basic");

  const [customers, setCustomers] = useState<RecordData[]>([]);
  const [items, setItems] = useState<RecordData[]>([]);
  const [warehouses, setWarehouses] = useState<RecordData[]>([]);
  const [loadingMasters, setLoadingMasters] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const [form, setForm] = useState({
    sales_order_id: "",
    order_number: "Auto-generated by system",
    order_date: today(),
    status: "Draft",
    customer_id: "",
    customer_reference: "",
    quotation_reference: "",
    channel: "B2B",
    currency: "INR",
    contact_person: "",
    contact_email: "",
    contact_phone: "",
    billing_address: "",
    shipping_address: "",
    customer_state: "",
    payment_terms: "",
    credit_limit: 0,
    warehouse_id: "",
    delivery_date: "",
    delivery_instructions: "",
    freight_charges: "0",
    other_charges: "0",
    tax_applicable: true,
    gst_percentage: "18",
    is_igst: false,
    warranty_terms: "",
    cancellation_terms: "",
    special_instructions: "",
    internal_notes: "",
  });

  const [lines, setLines] = useState<OrderLine[]>([newLine()]);

  const request = useCallback(async (path: string, init?: RequestInit) => {
    const response = await fetch(`${API}${path}`, {
      ...init,
      headers: {
        ...(init?.body ? { "Content-Type": "application/json" } : {}),
        ...(init?.headers || {}),
      },
    });

    const result = await response.json().catch(() => null);

    if (!response.ok) {
      throw new Error(
        result?.message || result?.error || `API request failed (${response.status}): ${path}`
      );
    }
    return result;
  }, []);

  useEffect(() => {
    let cancelled = false;

    async function loadMasters() {
      setLoadingMasters(true);
      setError("");

      const results = await Promise.allSettled([
        request("/api/customers"),
        request("/api/items"),
        request("/api/warehouses"),
      ]);

      if (cancelled) return;

      if (results[0].status === "fulfilled") {
        setCustomers(
          getRows(results[0].value).filter(
            c => String(c.status ?? "Active").toLowerCase() === "active"
          )
        );
      } else {
        setError("Customer Master could not load. Verify GET /api/customers.");
      }

      if (results[1].status === "fulfilled") {
        setItems(
          getRows(results[1].value).filter(
            i => String(i.status ?? "Active").toLowerCase() === "active"
          )
        );
      } else {
        setError("Item Master could not load. Verify GET /api/items.");
      }

      if (results[2].status === "fulfilled") {
        setWarehouses(
          getRows(results[2].value).filter(
            w => String(w.status ?? "Active").toLowerCase() === "active"
          )
        );
      } else {
        setError("Warehouse Master could not load. Verify GET /api/warehouses.");
      }

      setLoadingMasters(false);
    }

    void loadMasters();

    return () => {
      cancelled = true;
    };
  }, [request]);

  const selectedCustomer = useMemo(
    () => customers.find(c => recordId(c) === form.customer_id),
    [customers, form.customer_id]
  );

  const selectedWarehouse = useMemo(
    () => warehouses.find(w => recordId(w) === form.warehouse_id),
    [warehouses, form.warehouse_id]
  );

  // Customer Master selection automatically populates customer information.
  function selectCustomer(customerId: string) {
    const c = customers.find(x => recordId(x) === customerId);

    setForm(prev => ({
      ...prev,
      customer_id: customerId,
      contact_person: c
        ? String(c.contact_person_name ?? c.contact_person ?? "")
        : "",
      contact_email: c
        ? String(c.email ?? c.contact_email ?? "")
        : "",
      contact_phone: c
        ? String(c.phone ?? c.contact_phone ?? "")
        : "",
      billing_address: c
        ? String(c.billing_address ?? c.address ?? "")
        : "",
      shipping_address: c
        ? String(c.shipping_address ?? c.delivery_address ?? c.address ?? "")
        : "",
      customer_state: c
        ? String(c.state ?? c.state_name ?? "")
        : "",
      payment_terms: c
        ? String(c.payment_terms ?? c.paymentTerms ?? "")
        : "",
      credit_limit: c
        ? Number(c.credit_limit ?? c.creditLimit ?? 0)
        : 0,
      currency: c
        ? String(c.currency ?? "INR").toUpperCase()
        : "INR",
      channel: c
        ? String(c.customer_type ?? c.channel ?? "B2B").toUpperCase()
        : "B2B",
    }));

    setActiveTab("customer");
  }

  // Item Master selection automatically populates UOM and available master pricing.
  function selectItem(index: number, itemId: string) {
    const item = items.find(i => recordId(i) === itemId);

    setLines(prev => prev.map((line, i) => {
      if (i !== index) return line;

      if (!item) return { ...line, ...newLine() };

      return {
        ...line,
        item_id: itemId,
        item_code: String(item.item_code ?? item.code ?? item.sku ?? ""),
        item_name: itemName(item),
        uom: String(item.uom ?? item.base_uom ?? item.uom_code ?? "EA"),
        unit_price: Number(
          item.selling_price ?? item.sale_price ?? item.unit_price ?? item.list_price ?? 0
        ),
        tax_percent: Number(
          item.gst_percentage ?? item.tax_rate ?? item.tax_percent ?? 18
        ),
      };
    }));
  }

  // Auto-detect intra-state vs inter-state tax where master data supports it.
  function selectWarehouse(warehouseId: string) {
    const wh = warehouses.find(w => recordId(w) === warehouseId);
    const customerState = String(
      selectedCustomer?.state_code ?? selectedCustomer?.state ?? selectedCustomer?.state_name ?? ""
    ).trim().toLowerCase();
    const warehouseState = String(
      wh?.state_code ?? wh?.state ?? wh?.state_name ?? ""
    ).trim().toLowerCase();

    setForm(prev => ({
      ...prev,
      warehouse_id: warehouseId,
      is_igst: Boolean(
        customerState && warehouseState && customerState !== warehouseState
      ),
    }));
  }

  const totals = useMemo(() => {
    const subtotal = lines.reduce(
      (sum, line) => sum + Math.max(0, line.quantity) * Math.max(0, line.unit_price),
      0
    );

    const discount = lines.reduce((sum, line) => {
      const gross = Math.max(0, line.quantity) * Math.max(0, line.unit_price);
      return sum + gross * Math.min(100, Math.max(0, line.discount_percent)) / 100;
    }, 0);

    const taxable = Math.max(0, subtotal - discount);

    const tax = form.tax_applicable
      ? lines.reduce((sum, line) => {
          const gross = Math.max(0, line.quantity) * Math.max(0, line.unit_price);
          const net = gross * (1 - Math.min(100, Math.max(0, line.discount_percent)) / 100);
          return sum + net * Math.max(0, line.tax_percent) / 100;
        }, 0)
      : 0;

    const freight = Math.max(0, Number(form.freight_charges) || 0);
    const other = Math.max(0, Number(form.other_charges) || 0);

    return {
      subtotal,
      discount,
      taxable,
      tax,
      freight,
      other,
      grandTotal: taxable + tax + freight + other,
    };
  }, [lines, form.tax_applicable, form.freight_charges, form.other_charges]);

  function updateLine(index: number, patch: Partial<OrderLine>) {
    setLines(prev => prev.map((line, i) => i === index ? { ...line, ...patch } : line));
  }

  function validateTab(tab: TabKey) {
    if (tab === "basic") {
      if (!form.order_date) return "Order date is required.";
      if (!form.channel) return "Sales channel is required.";
    }

    if (tab === "customer" && !form.customer_id) {
      return "Select a customer from Customer Master.";
    }

    if (tab === "items") {
      if (!lines.length || lines.some(l =>
        !l.item_id ||
        !Number.isFinite(l.quantity) ||
        l.quantity <= 0 ||
        !Number.isFinite(l.unit_price) ||
        l.unit_price < 0 ||
        l.discount_percent < 0 ||
        l.discount_percent > 100 ||
        l.tax_percent < 0
      )) {
        return "Select an active item and enter a valid quantity, price, discount and tax for each line.";
      }
    }

    if (tab === "delivery") {
      if (!form.warehouse_id) return "Select an active outbound warehouse.";
      if (form.delivery_date && form.delivery_date < form.order_date) {
        return "Requested delivery date cannot be before the order date.";
      }
    }

    return "";
  }

  function goNext() {
    const validation = validateTab(activeTab);
    if (validation) {
      setError(validation);
      return;
    }

    setError("");
    const index = TABS.findIndex(t => t.key === activeTab);
    if (index < TABS.length - 1) setActiveTab(TABS[index + 1].key);
  }

  async function saveOrder() {
    setError("");
    setSuccess("");

    for (const tab of TABS) {
      const validation = validateTab(tab.key);
      if (validation) {
        setActiveTab(tab.key);
        setError(validation);
        return;
      }
    }

    setSaving(true);

    try {
      const payload = {
        customer_id: form.customer_id,
        customer_reference: form.customer_reference || null,
        quotation_reference: form.quotation_reference || null,
        channel: form.channel,
        currency: form.currency,
        warehouse_id: form.warehouse_id,
        requested_delivery_date: form.delivery_date || null,
        payment_terms: form.payment_terms || null,
        billing_address: form.billing_address || null,
        shipping_address: form.shipping_address || null,
        delivery_instructions: form.delivery_instructions || null,
        freight_charges: totals.freight,
        other_charges: totals.other,
        warranty_terms: form.warranty_terms || null,
        cancellation_terms: form.cancellation_terms || null,
        special_instructions: form.special_instructions || null,
        internal_notes: form.internal_notes || null,
        status: "Draft",
        lines: lines.map(l => ({
          item_id: l.item_id,
          ordered_qty: Number(l.quantity),
          uom: l.uom,
          unit_price: Number(l.unit_price),
          discount_percent: Number(l.discount_percent),
          tax_percent: Number(l.tax_percent),
        })),
        // UI estimate only; backend must recalculate all authoritative values.
        client_calculated_total: Number(totals.grandTotal.toFixed(2)),
      };

      await request("/api/orders", {
        method: "POST",
        body: JSON.stringify(payload),
      });

      setSuccess("Sales Order draft saved successfully.");
      setActiveTab("basic");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unable to save Sales Order.");
    } finally {
      setSaving(false);
    }
  }

  function Field({
    title,
    children,
  }: {
    title: string;
    children: React.ReactNode;
  }) {
    return (
      <div>
        <label className={labelClass}>{title}</label>
        {children}
      </div>
    );
  }

  return (
    <div className="space-y-5 pb-10">
      <PageBreadcrumb pageTitle="Create Sales Order" />

      <div className="rounded-2xl bg-gradient-to-r from-[#C8102E] to-[#005F99] p-5 text-white shadow-lg sm:p-7">
        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-white/75">
              FORTUNA SIMS · SALES & ORDER MANAGEMENT
            </p>
            <h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">
              Create Sales Order
            </h1>
            <p className="mt-2 text-sm text-white/85">
              Customer order entry with master-driven details and controlled fulfillment.
            </p>
          </div>
          <div className="rounded-xl border border-white/25 bg-white/10 p-3">
            <p className="text-xs text-white/75">Sales Order Number</p>
            <p className="mt-1 font-bold">Auto-generated by System</p>
          </div>
        </div>
      </div>

      {(error || success) && (
        <div className={`rounded-xl border p-3 text-sm ${
          error
            ? "border-rose-200 bg-rose-50 text-rose-800"
            : "border-emerald-200 bg-emerald-50 text-emerald-800"
        }`}>
          {error || success}
        </div>
      )}

      <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
        
{/* PO-style Sales Order Tabs */}
<div className="flex flex-wrap gap-1 border-b border-gray-200 p-2 dark:border-gray-800">
  {TABS.map((tab) => {
    const isActive = tab.key === activeTab;

    return (
      <button
        key={tab.key}
        type="button"
        onClick={() => {
          setActiveTab(tab.key);
          setError("");
        }}
        className={`relative rounded-lg px-3 py-2 text-sm font-semibold transition
          ${
            isActive
              ? "text-white shadow-sm"
              : "text-gray-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-white/5"
          }`}
        style={
          isActive
            ? { backgroundColor: RED }
            : undefined
        }
      >
        {tab.label}

        {isActive && (
          <span
            className="absolute -bottom-[6px] left-3 right-3 h-[3px] rounded-full"
            style={{ backgroundColor: BLUE }}
          />
        )}
      </button>
    );
  })}
</div>


        <div className="space-y-6 p-4 sm:p-6">
          {loadingMasters && (
            <p className="text-sm text-[#005F99]">
              <Loader2 className="mr-2 inline animate-spin" size={16} />
              Loading Customer, Item and Warehouse Masters…
            </p>
          )}

          {activeTab === "basic" && (
            <section className="space-y-4">
              <h2 className="text-lg font-extrabold text-gray-900 dark:text-white">
                1. Sales Order Basic Info
              </h2>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                <Field title="Sales Order Number">
                  <input disabled className={inputClass} value={form.order_number} />
                </Field>
                
<Field title="Order Date *">
  <input
    required
    type="date"
    className={`${inputClass} cursor-pointer`}
    value={form.order_date}
    onChange={(e) =>
      setForm((prev) => ({
        ...prev,
        order_date: e.target.value,
      }))
    }
  />
</Field>

                <Field title="Order Status">
                  <input disabled className={inputClass} value={form.status} />
                </Field>
                <Field title="Sales Channel *">
                  <select className={inputClass} value={form.channel}
                    onChange={e => setForm(p => ({ ...p, channel: e.target.value }))}>
                    <option value="B2B">B2B</option>
                    <option value="D2C">D2C</option>
                    <option value="RETAIL">Retail</option>
                  </select>
                </Field>
                <Field title="Currency">
                  <select className={inputClass} value={form.currency}
                    onChange={e => setForm(p => ({ ...p, currency: e.target.value }))}>
                    {["INR", "USD", "EUR", "GBP", "AED", "SAR", "SGD"].map(c =>
                      <option key={c}>{c}</option>
                    )}
                  </select>
                </Field>
                <Field title="Customer PO / Reference">
                  <input className={inputClass} value={form.customer_reference}
                    onChange={e => setForm(p => ({ ...p, customer_reference: e.target.value }))}
                    placeholder="Customer purchase reference" />
                </Field>
                <Field title="Quotation Reference">
                  <input className={inputClass} value={form.quotation_reference}
                    onChange={e => setForm(p => ({ ...p, quotation_reference: e.target.value }))}
                    placeholder="Accepted quotation number, if applicable" />
                </Field>
              </div>
            </section>
          )}

          {activeTab === "customer" && (
            <section className="space-y-4">
              <h2 className="text-lg font-extrabold text-gray-900 dark:text-white">
                2. Customer Details
              </h2>
              <p className="text-xs text-gray-500">
                Customer data is fetched from Customer Master; no demo customers are hardcoded.
              </p>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                <div className="md:col-span-2">
                  <Field title="Select Customer Master *">
                    <select required className={inputClass} value={form.customer_id}
                      disabled={loadingMasters || !customers.length}
                      onChange={e => selectCustomer(e.target.value)}>
                      <option value="">
                        {loadingMasters ? "Loading customers…" : "Select active customer"}
                      </option>
                      {customers.map(c => (
                        <option key={recordId(c)} value={recordId(c)}>
                          {c.customer_code ?? c.code ?? recordId(c)} — {customerName(c)}
                        </option>
                      ))}
                    </select>
                  </Field>
                </div>
                <Field title="Contact Person">
                  <input className={inputClass} value={form.contact_person} readOnly />
                </Field>
                <Field title="Contact Email">
                  <input className={inputClass} value={form.contact_email} readOnly />
                </Field>
                <Field title="Contact Phone">
                  <input className={inputClass} value={form.contact_phone} readOnly />
                </Field>
                <Field title="Payment Terms">
                  <input className={inputClass} value={form.payment_terms} readOnly />
                </Field>
                <Field title="Credit Limit">
                  <input className={inputClass}
                    value={money(form.credit_limit, form.currency)} readOnly />
                </Field>
                <Field title="Billing Address">
                  <textarea className={inputClass} rows={3} value={form.billing_address}
                    readOnly />
                </Field>
                <Field title="Shipping Address">
                  <textarea className={inputClass} rows={3} value={form.shipping_address}
                    readOnly />
                </Field>
              </div>
              {!loadingMasters && !customers.length && (
                <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">
                  No active customers were returned by Customer Master. Verify the API response and customer status field.
                </p>
              )}
            </section>
          )}

          {activeTab === "items" && (
            <section className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <h2 className="text-lg font-extrabold text-gray-900 dark:text-white">
                  3. Item & Pricing Details
                </h2>
                <button type="button" onClick={() => setLines(p => [...p, newLine()])}
                  className="rounded-lg px-3 py-2 text-sm font-bold text-white"
                  style={{ backgroundColor: BLUE }}>
                  + Add Item
                </button>
              </div>
              <div className="overflow-x-auto rounded-xl border dark:border-gray-700">
                <table className="min-w-[1000px] w-full text-left text-sm">
                  <thead style={{ backgroundColor: RED }} className="text-white">
                    <tr>{["Item Master *", "UOM", "Quantity *", "Unit Price", "Discount %", "Tax %", "Line Total", ""].map(h =>
                      <th key={h} className="px-3 py-3 text-xs font-bold">{h}</th>
                    )}</tr>
                  </thead>
                  <tbody className="divide-y dark:divide-gray-800">
                    {lines.map((line, index) => {
                      const net = line.quantity * line.unit_price *
                        (1 - line.discount_percent / 100);
                      const lineTotal = net * (1 + line.tax_percent / 100);
                      return (
                        <tr key={`${line.item_id}-${index}`}>
                          <td className="min-w-[250px] px-3 py-2">
                            <select required className={inputClass} value={line.item_id}
                              onChange={e => selectItem(index, e.target.value)}>
                              <option value="">Select active item</option>
                              {items.map(item => (
                                <option key={recordId(item)} value={recordId(item)}>
                                  {item.item_code ?? item.code ?? item.sku ?? recordId(item)} — {itemName(item)}
                                </option>
                              ))}
                            </select>
                          </td>
                          <td className="px-3 py-2">{line.uom}</td>
                          <td className="w-24 px-3 py-2">
                            <input required type="number" min="0.001" step="0.001"
                              className={inputClass} value={line.quantity}
                              onChange={e => updateLine(index, { quantity: Number(e.target.value) })} />
                          </td>
                          <td className="w-32 px-3 py-2">
                            <input required type="number" min="0" step="0.01"
                              className={inputClass} value={line.unit_price}
                              onChange={e => updateLine(index, { unit_price: Number(e.target.value) })} />
                          </td>
                          <td className="w-24 px-3 py-2">
                            <input type="number" min="0" max="100" step="0.01"
                              className={inputClass} value={line.discount_percent}
                              onChange={e => updateLine(index, { discount_percent: Number(e.target.value) })} />
                          </td>
                          <td className="w-24 px-3 py-2">
                            <input type="number" min="0" step="0.01"
                              className={inputClass} value={line.tax_percent}
                              onChange={e => updateLine(index, { tax_percent: Number(e.target.value) })} />
                          </td>
                          <td className="whitespace-nowrap px-3 py-2 font-bold">
                            {money(Number.isFinite(lineTotal) ? lineTotal : 0, form.currency)}
                          </td>
                          <td className="px-3 py-2">
                            <button type="button" disabled={lines.length === 1}
                              onClick={() => setLines(p => p.filter((_, i) => i !== index))}
                              className="font-bold text-[#C8102E] disabled:opacity-30">
                              Remove
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
              {!items.length && !loadingMasters && (
                <p className="text-sm text-rose-600">No active items found in Item Master.</p>
              )}
            </section>
          )}

          {activeTab === "delivery" && (
            <section className="space-y-4">
              <h2 className="text-lg font-extrabold text-gray-900 dark:text-white">
                4. Delivery & Logistics
              </h2>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                <Field title="Outbound Warehouse *">
                  <select required className={inputClass} value={form.warehouse_id}
                    onChange={e => selectWarehouse(e.target.value)}>
                    <option value="">Select active warehouse</option>
                    {warehouses.map(w => (
                      <option key={recordId(w)} value={recordId(w)}>
                        {w.warehouse_code ?? w.code ?? ""} — {w.warehouse_name ?? w.name}
                      </option>
                    ))}
                  </select>
                </Field>
                <DateField
  label="Requested Delivery Date"
  value={form.delivery_date}
  min={form.order_date || undefined}
  onChange={(value) =>
    setForm((prev) => ({
      ...prev,
      delivery_date: value,
    }))
  }
/>
                <Field title="Delivery Address">
                  <input className={inputClass}
                    value={form.shipping_address || String(selectedWarehouse?.address ?? "")}
                    readOnly />
                </Field>
                <div className="md:col-span-2 xl:col-span-3">
                  <Field title="Delivery Instructions">
                    <textarea rows={3} className={inputClass}
                      value={form.delivery_instructions}
                      onChange={e => setForm(p => ({ ...p, delivery_instructions: e.target.value }))}
                      placeholder="Delivery window, handling requirements, contact instructions…" />
                  </Field>
                </div>
              </div>
            </section>
          )}

          {activeTab === "taxes" && (
            <section className="space-y-4">
              <h2 className="text-lg font-extrabold text-gray-900 dark:text-white">
                5. Taxes & Charges
              </h2>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                <Field title="Tax Applicable">
                  <select className={inputClass} value={String(form.tax_applicable)}
                    onChange={e => setForm(p => ({ ...p, tax_applicable: e.target.value === "true" }))}>
                    <option value="true">Yes</option><option value="false">No</option>
                  </select>
                </Field>
                <Field title="GST Rate (%)">
                  <input type="number" min="0" step="0.01" className={inputClass}
                    disabled={!form.tax_applicable} value={form.gst_percentage}
                    onChange={e => {
                      const rate = Number(e.target.value);
                      setForm(p => ({ ...p, gst_percentage: e.target.value }));
                      setLines(p => p.map(line => ({ ...line, tax_percent: rate >= 0 ? rate : 0 })));
                    }} />
                </Field>
                <Field title="Tax Type">
                  <input className={inputClass}
                    value={form.is_igst ? "IGST — Inter-state (detected)" : "CGST + SGST — Intra-state / default"}
                    readOnly />
                </Field>
                <Field title="Freight Charges">
                  <input type="number" min="0" step="0.01" className={inputClass}
                    value={form.freight_charges}
                    onChange={e => setForm(p => ({ ...p, freight_charges: e.target.value }))} />
                </Field>
                <Field title="Other Charges">
                  <input type="number" min="0" step="0.01" className={inputClass}
                    value={form.other_charges}
                    onChange={e => setForm(p => ({ ...p, other_charges: e.target.value }))} />
                </Field>
              </div>
              <div className="rounded-xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800/60">
                <h3 className="mb-3 font-extrabold dark:text-white">Order Summary</h3>
                {[
                  ["Subtotal", totals.subtotal],
                  ["Discount", -totals.discount],
                  ["Taxable Value", totals.taxable],
                  ["Estimated Tax", totals.tax],
                  ["Freight", totals.freight],
                  ["Other Charges", totals.other],
                ].map(([title, value]) => (
                  <div key={String(title)} className="flex justify-between py-1.5 text-sm">
                    <span className="text-gray-600 dark:text-gray-300">{title}</span>
                    <span className="font-semibold">{money(Number(value), form.currency)}</span>
                  </div>
                ))}
                <div className="mt-3 flex justify-between border-t pt-3 dark:border-gray-700">
                  <span className="font-extrabold dark:text-white">Estimated Grand Total</span>
                  <span className="text-xl font-extrabold" style={{ color: RED }}>
                    {money(totals.grandTotal, form.currency)}
                  </span>
                </div>
              </div>
            </section>
          )}

          {activeTab === "terms" && (
            <section className="space-y-4">
              <h2 className="text-lg font-extrabold text-gray-900 dark:text-white">
                6. Terms & Conditions
              </h2>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <Field title="Warranty / Service Terms">
                  <textarea rows={3} className={inputClass} value={form.warranty_terms}
                    onChange={e => setForm(p => ({ ...p, warranty_terms: e.target.value }))} />
                </Field>
                <Field title="Cancellation Terms">
                  <textarea rows={3} className={inputClass} value={form.cancellation_terms}
                    onChange={e => setForm(p => ({ ...p, cancellation_terms: e.target.value }))} />
                </Field>
                <Field title="Special Instructions">
                  <textarea rows={3} className={inputClass} value={form.special_instructions}
                    onChange={e => setForm(p => ({ ...p, special_instructions: e.target.value }))} />
                </Field>
                <Field title="Internal Notes">
                  <textarea rows={3} className={inputClass} value={form.internal_notes}
                    onChange={e => setForm(p => ({ ...p, internal_notes: e.target.value }))} />
                </Field>
              </div>
              <div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">
                <ShieldCheck className="mr-2 inline" size={18} />
                Save as Draft does not reserve stock. Customer status, credit exposure, final tax,
                order number and stock availability must be verified by the backend before approval.
              </div>
            </section>
          )}

          <div className="flex flex-col-reverse gap-2 border-t pt-4 dark:border-gray-800 sm:flex-row sm:items-center sm:justify-between">
            <button type="button" onClick={() => {
              const i = TABS.findIndex(t => t.key === activeTab);
              if (i > 0) setActiveTab(TABS[i - 1].key);
            }} disabled={activeTab === "basic"}
              className="inline-flex items-center justify-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-semibold disabled:opacity-40">
              <ArrowLeft size={16} /> Previous
            </button>
            <div className="flex flex-col gap-2 sm:flex-row">
              {activeTab !== "terms" && (
                <button type="button" onClick={goNext}
                  className="inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-bold text-white"
                  style={{ backgroundColor: BLUE }}>
                  Next Section <ArrowRight size={16} />
                </button>
              )}
              {activeTab === "terms" && (
                <button type="button" onClick={() => void saveOrder()} disabled={saving || loadingMasters}
                  className="inline-flex items-center justify-center gap-2 rounded-lg px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50"
                  style={{ backgroundColor: RED }}>
                  {saving ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}
                  {saving ? "Saving…" : "Save as Draft"}
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
